alias: Bedroom - test
trigger:
  platform: state
  entity_id: light.bedroom
  to: 'on'
#condition:
#  - platform: state
#    entity_id: light.bedroom
#    state: 'on'
#  - platform: numeric_state
#    entity_id: sun.sun
#    value_template: '{{ state.attributes.elevation }}'
#    below: 5
action:
  service: homeassistant.turn_on
  entity_id: script.bedroom_timer

